### PR TITLE
Improve test cases to check for the positive case as well

### PR DESCRIPTION
**Pull request by ackerleytng**
Hope you like this!

### CODE REVIEW

**Comment by tirkarthi** [comment]
Thanks @ackerleytng. This looks great and the tests are much nicer and robust now. Thanks for the reserved namespace too with useful information. Thanks a lot for the contribution. Merged 👍

**Comment by ackerleytng** [comment]
Will you be putting this on clojars? Would like to use this for my project!

**Comment by tirkarthi** [comment]
Sure, I will push a release tonight or before Monday.

**Comment by ackerleytng** [comment]
Thanks! I'm actually working on a version of the validator that takes a predicate instead of a list of regexes or numbers. Still need to work on test cases, might be able to put up a pull request by tomorrow!

**Comment by tirkarthi** [comment]
That's great. Please keep in the existing key `:regexes` and consider adding a new optional key like `:predicates` to the function. Feel free to open a new issue to discuss about this since this PR is merged.

**Pull request merged**
